version: "3.2"
services:
  petclinic:
    build: .
    ports: 
      - 8080:8080
    networks:
      - petnet
    depends_on:
      - pet-mysql-container
    restart: on-failure:3

  pet-mysql-container:
    image: mysql:5.7.8
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=petclinic
      - MYSQL_PASSWORD=petclinic
      - MYSQL_DATABASE=petclinic
    networks:
      - petnet
    volumes:
      - "pet-datavolume:/var/lib/mysql"

networks: 
  petnet:

volumes:
  pet-datavolume: